env:
  es6: true
  node: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'eslint-config-prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 6
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {}
ignorePatterns:
  - '__tests__/fixtures/'
  - 'dist/'
