name: Release

on:
  release:
    types: [created]

env:
  WORKFLOW_NODE_VERSION: '14'

jobs:
  npm:
    name: Publish to NPM registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.WORKFLOW_NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org/'

      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn run build

      - name: Publish
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
